artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/DESMOND135/ML-Book-Recommender-System/main/dataset.zip
  dataset_dir: dataset
  raw_data_dir: raw_data
  ingested_dir: ingested_data

data_validation_config:
  schema_dir: config/schema.yaml   # optional if you use schema
  books_csv_file: BX-Books.csv
  users_csv_file: BX-Users.csv
  ratings_csv_file: BX-Book-Ratings.csv
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects

data_transformation_config:
  transformed_data_dir: transformed_data
  transformed_train_file: train.csv
  transformed_test_file: test.csv
  test_size: 0.2
  random_state: 42

model_trainer_config:
  trained_model_dir: trained_models
  trained_model_name: model.pkl
  base_accuracy: 0.7
